version: 2

sources:
  - name: aws_staging_data
    description: 'sample db provided by w3 school'
    database: AWS_DB
    schema: staging
    tables:
      - name: agents
        description: 'agents table'
        columns:
           - name: agent_code
             description: 'agent code must unique and not be null'
             tests:
                - not_null
      - name: customer
        description: 'customer table'
        columns:
          - name: cust_code
            description: 'Customer code must be unique and not null'
            tests:
                - unique
                - not_null
      - name: orders
        description: 'orders table'


models:
    # customer_order_summary_model
    - name: customer_order_summary_model
      description: "Summary from aws_staging_data"
      columns:
          - name: cust_name
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

          - name: total_order_count
            description: "total_order_count"
            tests:
                - not_null

          - name: total_order_amount
            description: "total_order_amount"
            tests:
                - not_null

          - name: total_advance_amount
            description: "total_advance_amount"
            tests:
                - not_null
      
